### ISSUE TITLE
validationParameters.ValidIssuer: 'http://localhost:8000/' or validationParameters.ValidIssuers: 'null'. 

### ISSUE THREAD

**Issue by wuxiao-ling197** [casdoor/casdoor-dotnet-sdk-example#9]
![onemore](https://github.com/casdoor/casdoor-dotnet-sdk-example/assets/77096395/7ffb3788-b2cc-4236-8e0f-000003bfac98)

it`s me again . when I change run casdoor at prod , I could run the consoleApp to get token and some info , but one new error was exposed , it said the issuer is nor match or null , I can`t understand I already got the issuer url why it tlod me wrong ? what I got is :
![1](https://github.com/casdoor/casdoor-dotnet-sdk-example/assets/77096395/2f4a3149-fed3-4500-9ef9-33a1071f44d1)

**Comment by hsluoyz** [comment]
@wuxiao-ling197 I tested this repo (https://github.com/casdoor/casdoor-dotnet-sdk-example) and it runs well. If you have changed the code and make it crash, make sure to restore the code

**Comment by wuxiao-ling197** [comment]
no ,  I did't change any other code except the basic URL , I guess it maybe I bonded a new created cert to my organization , then I deleted this cert  this error is still existed

**Comment by hsluoyz** [comment]
Make sure all settings and the cert public key and private key are correct

![image](https://github.com/casdoor/casdoor-dotnet-sdk-example/assets/3787410/39821ef6-5d11-4a3a-ba20-02cd1fda9def)
